apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: solr
  ports:
    - protocol: TCP
      port: 8983
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: solr
          image: solr
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            runAsUser: 1000
          ports:
            - containerPort: 8983
          env:
            - name: SOLR_MODE
              value: solrcloud
          startupProbe:
            httpGet:
              path: /solr/admin/info/system
              port: 8983
              httpHeaders:
                - name: X-Kubernetes-Probe
                  value: Startup
            timeoutSeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/solr/data
              name: data
              subPath: solr
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 1000m
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: os
          operator: Equal
          value: windows
          effect: NoSchedule
      imagePullSecrets:
        - name: sitecore-docker-registry
      containers:
      - name: solr-init
        image: sitecore-xm1-solr-init
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-connection-string.txt
        - name: SOLR_CORE_PREFIX_NAME
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-core-prefix-name.txt
      restartPolicy: Never
  backoffLimit: 5
